### ISSUE TITLE
User does not have permission to create "log" or edit "settings.cfg" in "%ProgramFiles%"

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-app#196] opened 2017-03-17 20:50 UTC
Please use "%USERPROFILE%\\.alignak-app-develop" directory for:

- settings.cfg
- alignakapp.log

Start app as usere from "C:\Program Files\Alignak-app\alignak-app.exe"

![app-user-start-error](https://cloud.githubusercontent.com/assets/20840532/24105376/f4b1dfe0-0d84-11e7-8499-35e022eb09e9.jpg)

**Comment by algorys** [comment] 2017-03-20 08:35
Normally installer give rights to all users for `C:\Program Files\Alignak-app` so this should not be a problem.

You can also define log folder in `settings.cfg`.

How do you install application ?

FYW, installation folders was discussed on #186.

**Comment by spea1** [comment] 2017-03-20 14:40
Password security:
If the app is running on a Windows terminal server, then "settings.cfg" and "alignakapp.log" must be moved to the "% USERPROFILE%\\. alignak-app" directory.

**Comment by algorys** [comment] 2017-03-20 15:10
Normally, it is not recommended to store your password in your `settings.cfg` file, you should leave empty **username** and **password** or generate a `token` and set it in **username** option.

For teminal server connexion, I've not manage this case yet... Maybe I can define a variable to define "ROOT" app folder... (ex: `%ALIGNAKAPP_ROOT%`)

Like that I check at start if this var exist, if not I set default (`C:\Program Files` for Windows, etc...)

@spea1 If you are agree, rename your issue or close this one and open a new one ?

**Comment by spea1** [comment] 2017-03-20 15:40
For example, more users on a workstation with different settings in the "settings.cfg" how should that work?

**Comment by algorys** [comment] 2017-03-21 08:15
I do not know for the moment, but I have to look at how to do this kind of thing.

**Comment by spea1** [comment] 2017-03-21 10:07
I think this is very simple:

1. Check when launching the app if the "%USERPROFILE%\\Alignak-app" directory exists if not created it
2. Check when launching the app if the "%USERPROFILE%\\Alignak-app\\settings.cfg" file exists, if not
"copy "%ProgramFiles%\\Alignak-app\\settings_example.cfg" %USERPROFILE%\\Alignak-app\\settings.cfg""
3. Use "%USERPROFILE%\\Alignak-app" directory  for log file.

**Comment by algorys** [comment] 2017-03-21 14:14
In case of multi user (with a terminal server) it would be very practical indeed.

I am not against giving back `%USERAPPDATA%\Alignak-app` as other python Libs.

@mohierf your advice ?

**Comment by mohierf** [comment] 2017-03-21 14:55
IMHO, we should have two installation mode:
 - multi-users, with `settings.cfg` located in *c:\program files\Alignak-app*
 - single-user mode, with `settings.cfg` in *%USERPROFILE%\Alignak-app*

The installer may propose to choose the installation scheme?

**Comment by algorys** [comment] 2017-03-21 15:32
> The installer may propose to choose the installation scheme?

I can do this kind of things... The problem is to tell to App after where this files are stored...

**Comment by spea1** [comment] 2017-03-21 16:36
Create in  "%ProgramFiles%\Alignak-app\app_work_dir.cfg" with the content
**app_work_dir=%ProgramFiles%\Alignak-app**
or 
**app_work_dir=%USERPROFILE%\\.alignak-app**

**Comment by algorys** [comment] 2017-03-22 09:09
Ok. I'll try to resume:

* App define his **ROOT_FOLDER** in a file: `app_workdir.cfg` who is located on default folder: 
  * `%ProgramFiles%\Alignak-app` on Win
  * `~/.local/alignak_app` for Unix

* I think the `Config` section in `settings.cfg` is no more required after.
* Then `settings.cfg` and `alignakapp.log` files are stored / created inside **ROOT_FOLDER**

Like that user can define directory with needed rights more easily.

**Comment by algorys** [comment] 2017-03-24 16:02
You can now define folder where App write logs and search his `settings.cfg`.

**Closed as completed by algorys** 2017-03-24 16:02 UTC
